title: Salvium Protocol Blog
email: your-email@example.com
description: >-
  Official blog of the Salvium Protocol - Latest news and updates
baseurl: "/salvium"
url: "https://siko-ctrl.github.io"

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: <!--more-->

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier

# Jekyll Minifier settings
jekyll-minifier:
  exclude: ['*.min.js', '*.min.css']
  uglifier_args:
    harmony: true

# Pagination
paginate: 6
paginate_path: /blog/page/:num/

# Asset paths
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "images"
    values:
      image: true
  -
    scope:
      path: "New Blog Images"
    values:
      image: true
  -
    scope:
      path: "Salvium_assets"
    values:
      image: true
  -
    scope:
      path: "css"
    values:
      css: true
  -
    scope:
      path: "js"
    values:
      js: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:title/

# Include directories
include:
  - css
  - js
  - images
  - New Blog Images
  - Salvium_assets
  - _posts
  - blog
  - posts.json

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Keep files
keep_files:
  - css
  - js
  - images
  - New Blog Images
  - Salvium_assets
  - posts.json

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/
