title: Salvium Protocol Blog
email: your-email@example.com
description: >-
  Official blog of the Salvium Protocol - Latest news and updates
baseurl: "/salvium"
url: "https://siko-ctrl.github.io"

# Build settings
markdown: kramdown
permalink: pretty

# Performance optimizations
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]

# Blog settings
# paginate: 9
# paginate_path: /blog/page/:num/
excerpt_separator: <!--more-->

# Image optimization
picture:
  source: "images"
  output: "generated"
  suppress_warnings: true

# Cache settings
cache:
  type: filesystem
  path: .jekyll-cache
  strategy: default

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier

# Pagination Settings
pagination:
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
  indexpage: 'index'

# Jekyll Minifier settings
jekyll-minifier:
  preserve_php: true
  remove_comments: true
  remove_intertag_spaces: true
  remove_quotes: false
  compress_css: true
  compress_javascript: false
  simple_doctype: false
  remove_script_attributes: false
  remove_style_attributes: false
  remove_link_attributes: false
  remove_form_attributes: false
  remove_input_attributes: false
  remove_javascript_protocol: false
  remove_http_protocol: false
  remove_https_protocol: false
  preserve_line_breaks: false
  simple_boolean_attributes: false
  compress_js_templates: false

# Asset paths
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "images"
    values:
      image: true
  -
    scope:
      path: "New Blog Images"
    values:
      image: true
  -
    scope:
      path: "Salvium_assets"
    values:
      image: true
  -
    scope:
      path: "css"
    values:
      css: true
  -
    scope:
      path: "js"
    values:
      js: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:title/

# Include directories
include:
  - css
  - js
  - images
  - New Blog Images
  - Salvium_assets
  - _posts
  - blog
  - posts.json

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Keep files
keep_files:
  - css
  - js
  - images
  - New Blog Images
  - Salvium_assets
  - posts.json

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/
