title: Salvium Protocol Blog
email: your-email@example.com
description: >-
  Official blog of the Salvium Protocol - Latest news and updates
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: <!--more-->

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate

# Pagination
paginate: 6
paginate_path: /blog/page/:num/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
